// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ANALOGCLOCK_screen_init(void)
{
    ui_ANALOGCLOCK = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ANALOGCLOCK, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bg_analog = lv_img_create(ui_ANALOGCLOCK);
    lv_img_set_src(ui_bg_analog, &ui_img_bggg_png);
    lv_obj_set_width(ui_bg_analog, LV_SIZE_CONTENT);   /// 512
    lv_obj_set_height(ui_bg_analog, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_align(ui_bg_analog, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bg_analog, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bg_analog, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HOME1 = lv_btn_create(ui_ANALOGCLOCK);
    lv_obj_set_width(ui_HOME1, 38);
    lv_obj_set_height(ui_HOME1, 38);
    lv_obj_set_x(ui_HOME1, 4);
    lv_obj_set_y(ui_HOME1, 4);
    lv_obj_add_flag(ui_HOME1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HOME1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HOME1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HOME1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HOME1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HOME1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_HOME1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_HOME1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HOME2 = lv_img_create(ui_HOME1);
    lv_img_set_src(ui_HOME2, &ui_img_house_png);
    lv_obj_set_width(ui_HOME2, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_HOME2, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_align(ui_HOME2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HOME2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HOME2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HOME2, lv_color_hex(0x060505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HOME2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BACK1 = lv_btn_create(ui_ANALOGCLOCK);
    lv_obj_set_width(ui_BACK1, 40);
    lv_obj_set_height(ui_BACK1, 41);
    lv_obj_set_x(ui_BACK1, 195);
    lv_obj_set_y(ui_BACK1, 3);
    lv_obj_add_flag(ui_BACK1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BACK1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BACK1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BACK1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BACK1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BACK1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BACK1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BACK1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_img_create(ui_BACK1);
    lv_img_set_src(ui_Image5, &ui_img_backblack_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 26
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 26
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TimeAna = lv_obj_create(ui_ANALOGCLOCK);
    lv_obj_set_width(ui_TimeAna, 144);
    lv_obj_set_height(ui_TimeAna, 58);
    lv_obj_set_x(ui_TimeAna, -3);
    lv_obj_set_y(ui_TimeAna, -118);
    lv_obj_set_align(ui_TimeAna, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TimeAna, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TimeAna, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TimeAna, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TimeAna, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TimeAna, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_houranalog = lv_label_create(ui_TimeAna);
    lv_obj_set_width(ui_houranalog, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_houranalog, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_houranalog, -37);
    lv_obj_set_y(ui_houranalog, 0);
    lv_obj_set_align(ui_houranalog, LV_ALIGN_CENTER);
    lv_label_set_text(ui_houranalog, "03");
    lv_obj_set_style_text_color(ui_houranalog, lv_color_hex(0x02A5B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_houranalog, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_houranalog, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dau2cham = lv_label_create(ui_TimeAna);
    lv_obj_set_width(ui_dau2cham, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dau2cham, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dau2cham, 3);
    lv_obj_set_y(ui_dau2cham, -4);
    lv_obj_set_align(ui_dau2cham, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dau2cham, ":");
    lv_obj_set_style_text_color(ui_dau2cham, lv_color_hex(0x02A5B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dau2cham, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dau2cham, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_minanalog = lv_label_create(ui_TimeAna);
    lv_obj_set_width(ui_minanalog, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_minanalog, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_minanalog, 42);
    lv_obj_set_y(ui_minanalog, -1);
    lv_obj_set_align(ui_minanalog, LV_ALIGN_CENTER);
    lv_label_set_text(ui_minanalog, "59");
    lv_obj_set_style_text_color(ui_minanalog, lv_color_hex(0x02A5B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_minanalog, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_minanalog, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DayANA = lv_obj_create(ui_ANALOGCLOCK);
    lv_obj_set_width(ui_DayANA, 167);
    lv_obj_set_height(ui_DayANA, 34);
    lv_obj_set_x(ui_DayANA, 1);
    lv_obj_set_y(ui_DayANA, -82);
    lv_obj_set_align(ui_DayANA, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_DayANA, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DayANA, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DayANA, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_namedateAna = lv_label_create(ui_DayANA);
    lv_obj_set_width(ui_namedateAna, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_namedateAna, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_namedateAna, -46);
    lv_obj_set_y(ui_namedateAna, 0);
    lv_obj_set_align(ui_namedateAna, LV_ALIGN_CENTER);
    lv_label_set_text(ui_namedateAna, "Tue");
    lv_obj_set_style_text_color(ui_namedateAna, lv_color_hex(0x088CAB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_namedateAna, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_namedateAna, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dayana = lv_label_create(ui_DayANA);
    lv_obj_set_width(ui_dayana, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dayana, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dayana, 3);
    lv_obj_set_y(ui_dayana, -1);
    lv_obj_set_align(ui_dayana, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dayana, "4");
    lv_obj_set_style_text_color(ui_dayana, lv_color_hex(0x088CAB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dayana, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dayana, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_namemonthana = lv_label_create(ui_DayANA);
    lv_obj_set_width(ui_namemonthana, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_namemonthana, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_namemonthana, 55);
    lv_obj_set_y(ui_namemonthana, 0);
    lv_obj_set_align(ui_namemonthana, LV_ALIGN_CENTER);
    lv_label_set_text(ui_namemonthana, "Jul");
    lv_obj_set_style_text_color(ui_namemonthana, lv_color_hex(0x088CAB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_namemonthana, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_namemonthana, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ClockPannel = lv_obj_create(ui_ANALOGCLOCK);
    lv_obj_set_width(ui_ClockPannel, 180);
    lv_obj_set_height(ui_ClockPannel, 180);
    lv_obj_set_x(ui_ClockPannel, 0);
    lv_obj_set_y(ui_ClockPannel, 40);
    lv_obj_set_align(ui_ClockPannel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ClockPannel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ClockPannel, 500, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ClockPannel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ClockPannel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot1 = lv_obj_create(ui_ClockPannel);
    lv_obj_set_width(ui_dot1, 6);
    lv_obj_set_height(ui_dot1, 6);
    lv_obj_set_x(ui_dot1, -40);
    lv_obj_set_y(ui_dot1, 15);
    lv_obj_set_align(ui_dot1, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_dot1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot1, lv_color_hex(0x2C2FB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot2 = lv_obj_create(ui_ClockPannel);
    lv_obj_set_width(ui_dot2, 6);
    lv_obj_set_height(ui_dot2, 6);
    lv_obj_set_x(ui_dot2, -10);
    lv_obj_set_y(ui_dot2, 50);
    lv_obj_set_align(ui_dot2, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_dot2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot2, lv_color_hex(0x2C2FB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot3 = lv_obj_create(ui_ClockPannel);
    lv_obj_set_width(ui_dot3, 6);
    lv_obj_set_height(ui_dot3, 6);
    lv_obj_set_x(ui_dot3, -10);
    lv_obj_set_y(ui_dot3, -50);
    lv_obj_set_align(ui_dot3, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_dot3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot3, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot3, lv_color_hex(0x2C2FB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot4 = lv_obj_create(ui_ClockPannel);
    lv_obj_set_width(ui_dot4, 6);
    lv_obj_set_height(ui_dot4, 6);
    lv_obj_set_x(ui_dot4, -40);
    lv_obj_set_y(ui_dot4, -15);
    lv_obj_set_align(ui_dot4, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_dot4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot4, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot4, lv_color_hex(0x2C2FB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot5 = lv_obj_create(ui_ClockPannel);
    lv_obj_set_width(ui_dot5, 6);
    lv_obj_set_height(ui_dot5, 6);
    lv_obj_set_x(ui_dot5, 40);
    lv_obj_set_y(ui_dot5, -15);
    lv_obj_set_align(ui_dot5, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_dot5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot5, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot5, lv_color_hex(0x2C2FB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot6 = lv_obj_create(ui_ClockPannel);
    lv_obj_set_width(ui_dot6, 6);
    lv_obj_set_height(ui_dot6, 6);
    lv_obj_set_x(ui_dot6, 10);
    lv_obj_set_y(ui_dot6, -50);
    lv_obj_set_align(ui_dot6, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(ui_dot6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot6, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot6, lv_color_hex(0x2C2FB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot7 = lv_obj_create(ui_ClockPannel);
    lv_obj_set_width(ui_dot7, 6);
    lv_obj_set_height(ui_dot7, 6);
    lv_obj_set_x(ui_dot7, 10);
    lv_obj_set_y(ui_dot7, 50);
    lv_obj_clear_flag(ui_dot7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot7, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot7, lv_color_hex(0x2C2FB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot8 = lv_obj_create(ui_ClockPannel);
    lv_obj_set_width(ui_dot8, 6);
    lv_obj_set_height(ui_dot8, 6);
    lv_obj_set_x(ui_dot8, 40);
    lv_obj_set_y(ui_dot8, 15);
    lv_obj_clear_flag(ui_dot8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot8, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot8, lv_color_hex(0x2C2FB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clocknumber1 = lv_label_create(ui_ClockPannel);
    lv_obj_set_width(ui_clocknumber1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clocknumber1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_clocknumber1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_clocknumber1, "12");
    lv_obj_set_style_text_color(ui_clocknumber1, lv_color_hex(0x000746), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_clocknumber1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_clocknumber1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clocknumber2 = lv_label_create(ui_ClockPannel);
    lv_obj_set_width(ui_clocknumber2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clocknumber2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_clocknumber2, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_clocknumber2, "3");
    lv_obj_set_style_text_color(ui_clocknumber2, lv_color_hex(0x000746), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_clocknumber2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_clocknumber2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clocknumber3 = lv_label_create(ui_ClockPannel);
    lv_obj_set_width(ui_clocknumber3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clocknumber3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_clocknumber3, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_clocknumber3, "6");
    lv_obj_set_style_text_color(ui_clocknumber3, lv_color_hex(0x000746), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_clocknumber3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_clocknumber3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clocknumber4 = lv_label_create(ui_ClockPannel);
    lv_obj_set_width(ui_clocknumber4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clocknumber4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_clocknumber4, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_clocknumber4, "9");
    lv_obj_set_style_text_color(ui_clocknumber4, lv_color_hex(0x000746), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_clocknumber4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_clocknumber4, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clockhour = lv_img_create(ui_ClockPannel);
    lv_img_set_src(ui_clockhour, &ui_img_clock_hour_png);
    lv_obj_set_width(ui_clockhour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clockhour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_clockhour, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_clockhour, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_clockhour, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_clockmin = lv_img_create(ui_ClockPannel);
    lv_img_set_src(ui_clockmin, &ui_img_clock_min_png);
    lv_obj_set_width(ui_clockmin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clockmin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_clockmin, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_clockmin, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_clockmin, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_clocksec = lv_img_create(ui_ClockPannel);
    lv_img_set_src(ui_clocksec, &ui_img_clock_sec_png);
    lv_obj_set_width(ui_clocksec, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clocksec, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_clocksec, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_clocksec, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_clocksec, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_clocksec, 150);

    ui_clockcenter = lv_obj_create(ui_ClockPannel);
    lv_obj_set_width(ui_clockcenter, 8);
    lv_obj_set_height(ui_clockcenter, 8);
    lv_obj_set_align(ui_clockcenter, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_clockcenter, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_clockcenter, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_clockcenter, lv_color_hex(0x0CC9CB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clockcenter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_clockcenter, lv_color_hex(0x1937D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_clockcenter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_clockcenter, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_HOME1, ui_event_HOME1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BACK1, ui_event_BACK1, LV_EVENT_ALL, NULL);

}
