// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_SETALARM_screen_init(void)
{
    ui_SETALARM = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SETALARM, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BG = lv_img_create(ui_SETALARM);
    lv_img_set_src(ui_BG, &ui_img_bggg_png);
    lv_obj_set_width(ui_BG, LV_SIZE_CONTENT);   /// 512
    lv_obj_set_height(ui_BG, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_align(ui_BG, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BG, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HOME5 = lv_btn_create(ui_SETALARM);
    lv_obj_set_width(ui_HOME5, 38);
    lv_obj_set_height(ui_HOME5, 38);
    lv_obj_set_x(ui_HOME5, 4);
    lv_obj_set_y(ui_HOME5, 4);
    lv_obj_add_flag(ui_HOME5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HOME5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HOME5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HOME5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HOME5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HOME5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_HOME5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_HOME5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HOME6 = lv_img_create(ui_HOME5);
    lv_img_set_src(ui_HOME6, &ui_img_house_png);
    lv_obj_set_width(ui_HOME6, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_HOME6, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_align(ui_HOME6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HOME6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HOME6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HOME6, lv_color_hex(0x060505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HOME6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BACK4 = lv_btn_create(ui_SETALARM);
    lv_obj_set_width(ui_BACK4, 40);
    lv_obj_set_height(ui_BACK4, 41);
    lv_obj_set_x(ui_BACK4, 196);
    lv_obj_set_y(ui_BACK4, 4);
    lv_obj_add_flag(ui_BACK4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BACK4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BACK4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BACK4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BACK4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BACK4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BACK4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BACK4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BACK5 = lv_img_create(ui_BACK4);
    lv_img_set_src(ui_BACK5, &ui_img_backk_png);
    lv_obj_set_width(ui_BACK5, LV_SIZE_CONTENT);   /// 25
    lv_obj_set_height(ui_BACK5, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_BACK5, -1);
    lv_obj_set_y(ui_BACK5, -1);
    lv_obj_set_align(ui_BACK5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BACK5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BACK5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_HOME5, ui_event_HOME5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BACK4, ui_event_BACK4, LV_EVENT_ALL, NULL);

}
