// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_SETDAYTIME_screen_init(void)
{
    ui_SETDAYTIME = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SETDAYTIME, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_background3 = lv_img_create(ui_SETDAYTIME);
    lv_img_set_src(ui_background3, &ui_img_bggg_png);
    lv_obj_set_width(ui_background3, LV_SIZE_CONTENT);   /// 512
    lv_obj_set_height(ui_background3, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_align(ui_background3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_background3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_background3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HOME3 = lv_btn_create(ui_SETDAYTIME);
    lv_obj_set_width(ui_HOME3, 38);
    lv_obj_set_height(ui_HOME3, 38);
    lv_obj_set_x(ui_HOME3, 4);
    lv_obj_set_y(ui_HOME3, 4);
    lv_obj_add_flag(ui_HOME3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HOME3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HOME3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HOME3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HOME3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HOME3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_HOME3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_HOME3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HOME4 = lv_img_create(ui_HOME3);
    lv_img_set_src(ui_HOME4, &ui_img_house_png);
    lv_obj_set_width(ui_HOME4, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_HOME4, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_align(ui_HOME4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HOME4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HOME4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HOME4, lv_color_hex(0x060505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HOME4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BACK2 = lv_btn_create(ui_SETDAYTIME);
    lv_obj_set_width(ui_BACK2, 40);
    lv_obj_set_height(ui_BACK2, 41);
    lv_obj_set_x(ui_BACK2, 196);
    lv_obj_set_y(ui_BACK2, 4);
    lv_obj_add_flag(ui_BACK2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BACK2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BACK2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BACK2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BACK2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BACK2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BACK2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BACK2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BACK3 = lv_img_create(ui_BACK2);
    lv_img_set_src(ui_BACK3, &ui_img_backk_png);
    lv_obj_set_width(ui_BACK3, LV_SIZE_CONTENT);   /// 25
    lv_obj_set_height(ui_BACK3, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_BACK3, -1);
    lv_obj_set_y(ui_BACK3, -1);
    lv_obj_set_align(ui_BACK3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BACK3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BACK3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_img_create(ui_SETDAYTIME);
    lv_img_set_src(ui_Image3, &ui_img_clockwise_hour_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 18
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 98
    lv_obj_set_x(ui_Image3, -266);
    lv_obj_set_y(ui_Image3, 6);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_HOME3, ui_event_HOME3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BACK2, ui_event_BACK2, LV_EVENT_ALL, NULL);

}
