// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT date

lv_obj_t * ui_date_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_date;
    cui_date = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_date, 150);
    lv_obj_set_height(cui_date, 92);
    lv_obj_set_x(cui_date, 48);
    lv_obj_set_y(cui_date, -109);
    lv_obj_set_align(cui_date, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_date, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_date, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_date, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label2;
    cui_Label2 = lv_label_create(cui_date);
    lv_obj_set_width(cui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label2, 2);
    lv_obj_set_y(cui_Label2, -27);
    lv_obj_set_align(cui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label2, "Monday");
    lv_obj_set_style_text_color(cui_Label2, lv_color_hex(0xFAF0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label4;
    cui_Label4 = lv_label_create(cui_date);
    lv_obj_set_width(cui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label4, -23);
    lv_obj_set_y(cui_Label4, -1);
    lv_obj_set_align(cui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label4, "4");
    lv_obj_set_style_text_color(cui_Label4, lv_color_hex(0xFAF8F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label5;
    cui_Label5 = lv_label_create(cui_date);
    lv_obj_set_width(cui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label5, 21);
    lv_obj_set_y(cui_Label5, -2);
    lv_obj_set_align(cui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label5, "July");
    lv_obj_set_style_text_color(cui_Label5, lv_color_hex(0xFCFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label5, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label6;
    cui_Label6 = lv_label_create(cui_date);
    lv_obj_set_width(cui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label6, -2);
    lv_obj_set_y(cui_Label6, 22);
    lv_obj_set_align(cui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label6, "2023");
    lv_obj_set_style_text_color(cui_Label6, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label6, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_DATE_NUM);
    children[UI_COMP_DATE_DATE] = cui_date;
    children[UI_COMP_DATE_LABEL2] = cui_Label2;
    children[UI_COMP_DATE_LABEL4] = cui_Label4;
    children[UI_COMP_DATE_LABEL5] = cui_Label5;
    children[UI_COMP_DATE_LABEL6] = cui_Label6;
    lv_obj_add_event_cb(cui_date, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_date, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_date_create_hook(cui_date);
    return cui_date;
}

