// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_DATEGROUP_H
#define _UI_COMP_DATEGROUP_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT dategroup
#define UI_COMP_DATEGROUP_DATEGROUP 0
#define UI_COMP_DATEGROUP_NAMEDAY 1
#define UI_COMP_DATEGROUP_DATE1 2
#define UI_COMP_DATEGROUP_MONTH 3
#define UI_COMP_DATEGROUP_YEAR 4
#define _UI_COMP_DATEGROUP_NUM 5
lv_obj_t * ui_dategroup_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
