// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_comp_date_create_hook(lv_obj_t * comp)
{
}

void ui_comp_dategroup_create_hook(lv_obj_t * comp)
{
}

void ui_comp_temperaturegroup_create_hook(lv_obj_t * comp)
{
}
