// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_DATE_H
#define _UI_COMP_DATE_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT date
#define UI_COMP_DATE_DATE 0
#define UI_COMP_DATE_LABEL2 1
#define UI_COMP_DATE_LABEL4 2
#define UI_COMP_DATE_LABEL5 3
#define UI_COMP_DATE_LABEL6 4
#define _UI_COMP_DATE_NUM 5
lv_obj_t * ui_date_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
