// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_TEMPERATUREGROUP_H
#define _UI_COMP_TEMPERATUREGROUP_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT temperaturegroup
#define UI_COMP_TEMPERATUREGROUP_TEMPERATUREGROUP 0
#define UI_COMP_TEMPERATUREGROUP_TEMP 1
#define UI_COMP_TEMPERATUREGROUP_C 2
#define _UI_COMP_TEMPERATUREGROUP_NUM 3
lv_obj_t * ui_temperaturegroup_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
