// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT dategroup

lv_obj_t * ui_dategroup_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_dategroup;
    cui_dategroup = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_dategroup, 150);
    lv_obj_set_height(cui_dategroup, 92);
    lv_obj_set_x(cui_dategroup, 48);
    lv_obj_set_y(cui_dategroup, -109);
    lv_obj_set_align(cui_dategroup, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_dategroup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_dategroup, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_dategroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_dategroup, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_dategroup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_nameday;
    cui_nameday = lv_label_create(cui_dategroup);
    lv_obj_set_width(cui_nameday, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_nameday, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_nameday, 2);
    lv_obj_set_y(cui_nameday, -27);
    lv_obj_set_align(cui_nameday, LV_ALIGN_CENTER);
    lv_label_set_text(cui_nameday, "Tuesday");
    lv_obj_set_style_text_color(cui_nameday, lv_color_hex(0xD87BE3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_nameday, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_nameday, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_date1;
    cui_date1 = lv_label_create(cui_dategroup);
    lv_obj_set_width(cui_date1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_date1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_date1, -23);
    lv_obj_set_y(cui_date1, -1);
    lv_obj_set_align(cui_date1, LV_ALIGN_CENTER);
    lv_label_set_text(cui_date1, "4");
    lv_obj_set_style_text_color(cui_date1, lv_color_hex(0xCF0F0F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_date1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_date1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_month;
    cui_month = lv_label_create(cui_dategroup);
    lv_obj_set_width(cui_month, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_month, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_month, 12);
    lv_obj_set_y(cui_month, -1);
    lv_obj_set_align(cui_month, LV_ALIGN_CENTER);
    lv_label_set_text(cui_month, "July");
    lv_obj_set_style_text_color(cui_month, lv_color_hex(0x088CAB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_month, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_month, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_year;
    cui_year = lv_label_create(cui_dategroup);
    lv_obj_set_width(cui_year, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_year, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_year, -2);
    lv_obj_set_y(cui_year, 22);
    lv_obj_set_align(cui_year, LV_ALIGN_CENTER);
    lv_label_set_text(cui_year, "2023");
    lv_obj_set_style_text_color(cui_year, lv_color_hex(0xCCA41F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_year, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_year, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_DATEGROUP_NUM);
    children[UI_COMP_DATEGROUP_DATEGROUP] = cui_dategroup;
    children[UI_COMP_DATEGROUP_NAMEDAY] = cui_nameday;
    children[UI_COMP_DATEGROUP_DATE1] = cui_date1;
    children[UI_COMP_DATEGROUP_MONTH] = cui_month;
    children[UI_COMP_DATEGROUP_YEAR] = cui_year;
    lv_obj_add_event_cb(cui_dategroup, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_dategroup, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_dategroup_create_hook(cui_dategroup);
    return cui_dategroup;
}

