// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_HOME_screen_init(void)
{
    ui_HOME = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HOME, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HOME, lv_color_hex(0x020202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HOME, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HOME, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HOME, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_background = lv_img_create(ui_HOME);
    lv_img_set_src(ui_background, &ui_img_bggg_png);
    lv_obj_set_width(ui_background, LV_SIZE_CONTENT);   /// 512
    lv_obj_set_height(ui_background, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_align(ui_background, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_background, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_background, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_time = lv_obj_create(ui_HOME);
    lv_obj_set_width(ui_time, 155);
    lv_obj_set_height(ui_time, 103);
    lv_obj_set_x(ui_time, -41);
    lv_obj_set_y(ui_time, -59);
    lv_obj_set_align(ui_time, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_time, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hour = lv_label_create(ui_time);
    lv_obj_set_width(ui_hour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hour, -38);
    lv_obj_set_y(ui_hour, -19);
    lv_obj_set_align(ui_hour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hour, "03");
    lv_obj_set_style_text_color(ui_hour, lv_color_hex(0x02A5B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_hour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_hour, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_minute = lv_label_create(ui_time);
    lv_obj_set_width(ui_minute, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_minute, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_minute, 29);
    lv_obj_set_y(ui_minute, 13);
    lv_obj_set_align(ui_minute, LV_ALIGN_CENTER);
    lv_label_set_text(ui_minute, "59");
    lv_obj_set_style_text_color(ui_minute, lv_color_hex(0x5777E3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_minute, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_minute, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dategroup1 = lv_obj_create(ui_HOME);
    lv_obj_set_width(ui_dategroup1, 150);
    lv_obj_set_height(ui_dategroup1, 92);
    lv_obj_set_x(ui_dategroup1, 48);
    lv_obj_set_y(ui_dategroup1, -109);
    lv_obj_set_align(ui_dategroup1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_dategroup1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_dategroup1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dategroup1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_dategroup1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dategroup1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nameday1 = lv_label_create(ui_dategroup1);
    lv_obj_set_width(ui_nameday1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_nameday1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_nameday1, 2);
    lv_obj_set_y(ui_nameday1, -27);
    lv_obj_set_align(ui_nameday1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_nameday1, "Tuesday");
    lv_obj_set_style_text_color(ui_nameday1, lv_color_hex(0xD87BE3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_nameday1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_nameday1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date2 = lv_label_create(ui_dategroup1);
    lv_obj_set_width(ui_date2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date2, -23);
    lv_obj_set_y(ui_date2, -1);
    lv_obj_set_align(ui_date2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_date2, "4");
    lv_obj_set_style_text_color(ui_date2, lv_color_hex(0xCF0F0F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_date2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_month1 = lv_label_create(ui_dategroup1);
    lv_obj_set_width(ui_month1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_month1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_month1, 12);
    lv_obj_set_y(ui_month1, -1);
    lv_obj_set_align(ui_month1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_month1, "July");
    lv_obj_set_style_text_color(ui_month1, lv_color_hex(0x088CAB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_month1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_month1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_year1 = lv_label_create(ui_dategroup1);
    lv_obj_set_width(ui_year1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_year1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_year1, -2);
    lv_obj_set_y(ui_year1, 22);
    lv_obj_set_align(ui_year1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_year1, "2023");
    lv_obj_set_style_text_color(ui_year1, lv_color_hex(0xCCA41F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_year1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_year1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_halfsun = lv_img_create(ui_HOME);
    lv_img_set_src(ui_halfsun, &ui_img_sun_png);
    lv_obj_set_width(ui_halfsun, LV_SIZE_CONTENT);   /// 140
    lv_obj_set_height(ui_halfsun, LV_SIZE_CONTENT);    /// 250
    lv_obj_set_x(ui_halfsun, 98);
    lv_obj_set_y(ui_halfsun, 72);
    lv_obj_set_align(ui_halfsun, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_halfsun, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_halfsun, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_cloud = lv_img_create(ui_HOME);
    lv_img_set_src(ui_cloud, &ui_img_clouds_png);
    lv_obj_set_width(ui_cloud, LV_SIZE_CONTENT);   /// 168
    lv_obj_set_height(ui_cloud, LV_SIZE_CONTENT);    /// 192
    lv_obj_set_x(ui_cloud, 39);
    lv_obj_set_y(ui_cloud, 37);
    lv_obj_set_align(ui_cloud, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_cloud, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_cloud, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_temperaturegroup1 = lv_obj_create(ui_HOME);
    lv_obj_set_width(ui_temperaturegroup1, 100);
    lv_obj_set_height(ui_temperaturegroup1, 50);
    lv_obj_set_x(ui_temperaturegroup1, -67);
    lv_obj_set_y(ui_temperaturegroup1, 40);
    lv_obj_set_align(ui_temperaturegroup1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_temperaturegroup1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_temperaturegroup1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_temperaturegroup1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_temperaturegroup1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_temperaturegroup1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temp1 = lv_label_create(ui_temperaturegroup1);
    lv_obj_set_width(ui_temp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temp1, -23);
    lv_obj_set_y(ui_temp1, -2);
    lv_obj_set_align(ui_temp1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temp1, "25");
    lv_label_set_recolor(ui_temp1, "true");
    lv_obj_set_style_text_color(ui_temp1, lv_color_hex(0xFA0606), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temp1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temp1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_C1 = lv_label_create(ui_temperaturegroup1);
    lv_obj_set_width(ui_C1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_C1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_C1, 15);
    lv_obj_set_y(ui_C1, -2);
    lv_obj_set_align(ui_C1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_C1, "°C");
    lv_obj_set_style_text_color(ui_C1, lv_color_hex(0xFE0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_C1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_C1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hum = lv_obj_create(ui_HOME);
    lv_obj_set_width(ui_hum, 100);
    lv_obj_set_height(ui_hum, 50);
    lv_obj_set_x(ui_hum, -68);
    lv_obj_set_y(ui_hum, 78);
    lv_obj_set_align(ui_hum, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_hum, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_hum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_hum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_hum, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_hum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rain = lv_img_create(ui_hum);
    lv_img_set_src(ui_rain, &ui_img_rain_png);
    lv_obj_set_width(ui_rain, LV_SIZE_CONTENT);   /// 14
    lv_obj_set_height(ui_rain, LV_SIZE_CONTENT);    /// 19
    lv_obj_set_x(ui_rain, -33);
    lv_obj_set_y(ui_rain, -3);
    lv_obj_set_align(ui_rain, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rain, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_rain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_rain, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humm = lv_label_create(ui_hum);
    lv_obj_set_width(ui_humm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humm, -2);
    lv_obj_set_y(ui_humm, -2);
    lv_obj_set_align(ui_humm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humm, "40");
    lv_obj_set_style_text_color(ui_humm, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humm, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AirQuality = lv_obj_create(ui_HOME);
    lv_obj_set_width(ui_AirQuality, 172);
    lv_obj_set_height(ui_AirQuality, 33);
    lv_obj_set_x(ui_AirQuality, -33);
    lv_obj_set_y(ui_AirQuality, 140);
    lv_obj_set_align(ui_AirQuality, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AirQuality, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AirQuality, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AirQuality, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AirQuality, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AirQuality, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_air = lv_label_create(ui_AirQuality);
    lv_obj_set_width(ui_air, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_air, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_air, -37);
    lv_obj_set_y(ui_air, 6);
    lv_obj_set_align(ui_air, LV_ALIGN_CENTER);
    lv_label_set_text(ui_air, "Air Quality: ");
    lv_obj_set_style_text_color(ui_air, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_air, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ppm = lv_label_create(ui_AirQuality);
    lv_obj_set_width(ui_ppm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ppm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ppm, 24);
    lv_obj_set_y(ui_ppm, 7);
    lv_obj_set_align(ui_ppm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ppm, "100 ");
    lv_obj_set_style_text_color(ui_ppm, lv_color_hex(0x26AAA8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ppm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnmenu = lv_btn_create(ui_HOME);
    lv_obj_set_width(ui_btnmenu, 56);
    lv_obj_set_height(ui_btnmenu, 28);
    lv_obj_set_x(ui_btnmenu, 1);
    lv_obj_set_y(ui_btnmenu, 2);
    lv_obj_add_flag(ui_btnmenu, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnmenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnmenu1 = lv_label_create(ui_btnmenu);
    lv_obj_set_width(ui_btnmenu1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_btnmenu1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_btnmenu1, 0);
    lv_obj_set_y(ui_btnmenu1, -1);
    lv_obj_set_align(ui_btnmenu1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_btnmenu1, "MENU");

    ui_Label7 = lv_label_create(ui_HOME);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -43);
    lv_obj_set_y(ui_Label7, 76);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "%");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_HOME);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 28);
    lv_obj_set_y(ui_Label8, 146);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "PPM");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0x26AAA8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnmenu, ui_event_btnmenu, LV_EVENT_ALL, NULL);

}
