// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_SETALARM_screen_init(void)
{
    ui_SETALARM = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SETALARM, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BG = lv_img_create(ui_SETALARM);
    lv_img_set_src(ui_BG, &ui_img_bggg_png);
    lv_obj_set_width(ui_BG, LV_SIZE_CONTENT);   /// 512
    lv_obj_set_height(ui_BG, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_align(ui_BG, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BG, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HOME5 = lv_btn_create(ui_SETALARM);
    lv_obj_set_width(ui_HOME5, 38);
    lv_obj_set_height(ui_HOME5, 38);
    lv_obj_set_x(ui_HOME5, 4);
    lv_obj_set_y(ui_HOME5, 4);
    lv_obj_add_flag(ui_HOME5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HOME5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HOME5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HOME5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HOME5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HOME5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_HOME5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_HOME5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HOME6 = lv_img_create(ui_HOME5);
    lv_img_set_src(ui_HOME6, &ui_img_house_png);
    lv_obj_set_width(ui_HOME6, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_HOME6, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_align(ui_HOME6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HOME6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HOME6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HOME6, lv_color_hex(0x060505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HOME6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BACK4 = lv_btn_create(ui_SETALARM);
    lv_obj_set_width(ui_BACK4, 40);
    lv_obj_set_height(ui_BACK4, 41);
    lv_obj_set_x(ui_BACK4, 196);
    lv_obj_set_y(ui_BACK4, 4);
    lv_obj_add_flag(ui_BACK4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BACK4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BACK4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BACK4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BACK4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BACK4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BACK4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BACK4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BACK5 = lv_img_create(ui_BACK4);
    lv_img_set_src(ui_BACK5, &ui_img_backk_png);
    lv_obj_set_width(ui_BACK5, LV_SIZE_CONTENT);   /// 25
    lv_obj_set_height(ui_BACK5, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_BACK5, -1);
    lv_obj_set_y(ui_BACK5, -1);
    lv_obj_set_align(ui_BACK5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BACK5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BACK5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_SETALARM);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -3);
    lv_obj_set_y(ui_Label2, 14);
    lv_obj_set_align(ui_Label2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label2, "SET ALARM");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x0CBCEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_alarm1 = lv_obj_create(ui_SETALARM);
    lv_obj_set_width(ui_alarm1, 212);
    lv_obj_set_height(ui_alarm1, 69);
    lv_obj_set_x(ui_alarm1, 0);
    lv_obj_set_y(ui_alarm1, -72);
    lv_obj_set_align(ui_alarm1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_alarm1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_alarm1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_alarm1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_alarm1, lv_color_hex(0x293062), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_alarm1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_alarm1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_alarm1, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_alarm1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_alarm1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_alarm1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_alarm1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeAna2 = lv_obj_create(ui_alarm1);
    lv_obj_set_width(ui_TimeAna2, 144);
    lv_obj_set_height(ui_TimeAna2, 58);
    lv_obj_set_x(ui_TimeAna2, -38);
    lv_obj_set_y(ui_TimeAna2, -2);
    lv_obj_set_align(ui_TimeAna2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TimeAna2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TimeAna2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TimeAna2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TimeAna2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TimeAna2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_houranalog2 = lv_label_create(ui_TimeAna2);
    lv_obj_set_width(ui_houranalog2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_houranalog2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_houranalog2, -37);
    lv_obj_set_y(ui_houranalog2, 0);
    lv_obj_set_align(ui_houranalog2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_houranalog2, "05");
    lv_obj_set_style_text_color(ui_houranalog2, lv_color_hex(0x02A5B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_houranalog2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_houranalog2, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dau2cham2 = lv_label_create(ui_TimeAna2);
    lv_obj_set_width(ui_dau2cham2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dau2cham2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dau2cham2, 3);
    lv_obj_set_y(ui_dau2cham2, -4);
    lv_obj_set_align(ui_dau2cham2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dau2cham2, ":");
    lv_obj_set_style_text_color(ui_dau2cham2, lv_color_hex(0x02A5B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dau2cham2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dau2cham2, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_minanalog2 = lv_label_create(ui_TimeAna2);
    lv_obj_set_width(ui_minanalog2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_minanalog2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_minanalog2, 42);
    lv_obj_set_y(ui_minanalog2, -1);
    lv_obj_set_align(ui_minanalog2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_minanalog2, "00");
    lv_obj_set_style_text_color(ui_minanalog2, lv_color_hex(0x02A5B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_minanalog2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_minanalog2, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch1 = lv_switch_create(ui_alarm1);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, 67);
    lv_obj_set_y(ui_Switch1, -7);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_alarm1);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 65);
    lv_obj_set_y(ui_Label11, 21);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Wake Up!");

    ui_alarm2 = lv_obj_create(ui_SETALARM);
    lv_obj_set_width(ui_alarm2, 212);
    lv_obj_set_height(ui_alarm2, 69);
    lv_obj_set_x(ui_alarm2, 0);
    lv_obj_set_y(ui_alarm2, -1);
    lv_obj_set_align(ui_alarm2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_alarm2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_alarm2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_alarm2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_alarm2, lv_color_hex(0x293062), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_alarm2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_alarm2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_alarm2, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_alarm2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_alarm2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_alarm2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_alarm2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeAna3 = lv_obj_create(ui_alarm2);
    lv_obj_set_width(ui_TimeAna3, 144);
    lv_obj_set_height(ui_TimeAna3, 58);
    lv_obj_set_x(ui_TimeAna3, -38);
    lv_obj_set_y(ui_TimeAna3, -2);
    lv_obj_set_align(ui_TimeAna3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TimeAna3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TimeAna3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TimeAna3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TimeAna3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TimeAna3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_houranalog3 = lv_label_create(ui_TimeAna3);
    lv_obj_set_width(ui_houranalog3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_houranalog3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_houranalog3, -37);
    lv_obj_set_y(ui_houranalog3, 0);
    lv_obj_set_align(ui_houranalog3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_houranalog3, "06");
    lv_obj_set_style_text_color(ui_houranalog3, lv_color_hex(0x02A5B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_houranalog3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_houranalog3, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dau2cham3 = lv_label_create(ui_TimeAna3);
    lv_obj_set_width(ui_dau2cham3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dau2cham3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dau2cham3, 3);
    lv_obj_set_y(ui_dau2cham3, -4);
    lv_obj_set_align(ui_dau2cham3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dau2cham3, ":");
    lv_obj_set_style_text_color(ui_dau2cham3, lv_color_hex(0x02A5B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dau2cham3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dau2cham3, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_minanalog3 = lv_label_create(ui_TimeAna3);
    lv_obj_set_width(ui_minanalog3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_minanalog3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_minanalog3, 42);
    lv_obj_set_y(ui_minanalog3, -1);
    lv_obj_set_align(ui_minanalog3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_minanalog3, "00");
    lv_obj_set_style_text_color(ui_minanalog3, lv_color_hex(0x02A5B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_minanalog3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_minanalog3, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch2 = lv_switch_create(ui_alarm2);
    lv_obj_set_width(ui_Switch2, 50);
    lv_obj_set_height(ui_Switch2, 25);
    lv_obj_set_x(ui_Switch2, 67);
    lv_obj_set_y(ui_Switch2, -7);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_alarm2);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 65);
    lv_obj_set_y(ui_Label10, 21);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Breakfast");

    ui_ok2 = lv_btn_create(ui_SETALARM);
    lv_obj_set_width(ui_ok2, 65);
    lv_obj_set_height(ui_ok2, 34);
    lv_obj_set_x(ui_ok2, -63);
    lv_obj_set_y(ui_ok2, -11);
    lv_obj_set_align(ui_ok2, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_ok2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ok2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label13 = lv_label_create(ui_ok2);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "CHANGE");

    ui_alarm3 = lv_obj_create(ui_SETALARM);
    lv_obj_set_width(ui_alarm3, 212);
    lv_obj_set_height(ui_alarm3, 69);
    lv_obj_set_x(ui_alarm3, 0);
    lv_obj_set_y(ui_alarm3, 70);
    lv_obj_set_align(ui_alarm3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_alarm3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_alarm3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_alarm3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_alarm3, lv_color_hex(0x293062), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_alarm3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_alarm3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_alarm3, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_alarm3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_alarm3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_alarm3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_alarm3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeAna4 = lv_obj_create(ui_alarm3);
    lv_obj_set_width(ui_TimeAna4, 144);
    lv_obj_set_height(ui_TimeAna4, 58);
    lv_obj_set_x(ui_TimeAna4, -38);
    lv_obj_set_y(ui_TimeAna4, -2);
    lv_obj_set_align(ui_TimeAna4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TimeAna4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TimeAna4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TimeAna4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TimeAna4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TimeAna4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_houranalog4 = lv_label_create(ui_TimeAna4);
    lv_obj_set_width(ui_houranalog4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_houranalog4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_houranalog4, -37);
    lv_obj_set_y(ui_houranalog4, 0);
    lv_obj_set_align(ui_houranalog4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_houranalog4, "07");
    lv_obj_set_style_text_color(ui_houranalog4, lv_color_hex(0x02A5B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_houranalog4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_houranalog4, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dau2cham4 = lv_label_create(ui_TimeAna4);
    lv_obj_set_width(ui_dau2cham4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dau2cham4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dau2cham4, 3);
    lv_obj_set_y(ui_dau2cham4, -4);
    lv_obj_set_align(ui_dau2cham4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dau2cham4, ":");
    lv_obj_set_style_text_color(ui_dau2cham4, lv_color_hex(0x02A5B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dau2cham4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dau2cham4, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_minanalog4 = lv_label_create(ui_TimeAna4);
    lv_obj_set_width(ui_minanalog4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_minanalog4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_minanalog4, 42);
    lv_obj_set_y(ui_minanalog4, -1);
    lv_obj_set_align(ui_minanalog4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_minanalog4, "00");
    lv_obj_set_style_text_color(ui_minanalog4, lv_color_hex(0x02A5B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_minanalog4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_minanalog4, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch3 = lv_switch_create(ui_alarm3);
    lv_obj_set_width(ui_Switch3, 50);
    lv_obj_set_height(ui_Switch3, 25);
    lv_obj_set_x(ui_Switch3, 67);
    lv_obj_set_y(ui_Switch3, -7);
    lv_obj_set_align(ui_Switch3, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch3, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_alarm3);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 6);
    lv_obj_set_y(ui_Label12, -2);
    lv_obj_set_align(ui_Label12, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_Label12, "Go to School");

    ui_ok3 = lv_btn_create(ui_SETALARM);
    lv_obj_set_width(ui_ok3, 65);
    lv_obj_set_height(ui_ok3, 34);
    lv_obj_set_x(ui_ok3, 63);
    lv_obj_set_y(ui_ok3, -11);
    lv_obj_set_align(ui_ok3, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_ok3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ok3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label14 = lv_label_create(ui_ok3);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "OK");

    lv_obj_add_event_cb(ui_HOME5, ui_event_HOME5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BACK4, ui_event_BACK4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ok2, ui_event_ok2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ok3, ui_event_ok3, LV_EVENT_ALL, NULL);

}
