// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_SETTIME_screen_init(void)
{
    ui_SETTIME = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SETTIME, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bgsettime = lv_img_create(ui_SETTIME);
    lv_img_set_src(ui_bgsettime, &ui_img_bggg_png);
    lv_obj_set_width(ui_bgsettime, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_bgsettime, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_align(ui_bgsettime, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bgsettime, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bgsettime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_titlesdt1 = lv_label_create(ui_SETTIME);
    lv_obj_set_width(ui_titlesdt1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_titlesdt1, LV_SIZE_CONTENT);    /// -83
    lv_obj_set_x(ui_titlesdt1, -3);
    lv_obj_set_y(ui_titlesdt1, 14);
    lv_obj_set_align(ui_titlesdt1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_titlesdt1, "SET TIME");
    lv_obj_set_style_text_color(ui_titlesdt1, lv_color_hex(0x0CBCEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_titlesdt1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ok = lv_btn_create(ui_SETTIME);
    lv_obj_set_width(ui_ok, 65);
    lv_obj_set_height(ui_ok, 35);
    lv_obj_set_x(ui_ok, 2);
    lv_obj_set_y(ui_ok, 97);
    lv_obj_set_align(ui_ok, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ok, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ok, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_ok);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "OK");

    ui_titlesdt2 = lv_label_create(ui_SETTIME);
    lv_obj_set_width(ui_titlesdt2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_titlesdt2, LV_SIZE_CONTENT);    /// -83
    lv_obj_set_x(ui_titlesdt2, -55);
    lv_obj_set_y(ui_titlesdt2, 72);
    lv_obj_set_align(ui_titlesdt2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_titlesdt2, "SET HOUR");
    lv_obj_set_style_text_color(ui_titlesdt2, lv_color_hex(0x0CBCEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_titlesdt2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_titlesdt3 = lv_label_create(ui_SETTIME);
    lv_obj_set_width(ui_titlesdt3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_titlesdt3, LV_SIZE_CONTENT);    /// -83
    lv_obj_set_x(ui_titlesdt3, 55);
    lv_obj_set_y(ui_titlesdt3, 72);
    lv_obj_set_align(ui_titlesdt3, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_titlesdt3, "SET MINUTE");
    lv_obj_set_style_text_color(ui_titlesdt3, lv_color_hex(0x0CBCEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_titlesdt3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bgroller = lv_img_create(ui_SETTIME);
    lv_img_set_src(ui_bgroller, &ui_img_216451335);
    lv_obj_set_width(ui_bgroller, LV_SIZE_CONTENT);   /// 52
    lv_obj_set_height(ui_bgroller, LV_SIZE_CONTENT);    /// 102
    lv_obj_set_x(ui_bgroller, -54);
    lv_obj_set_y(ui_bgroller, -9);
    lv_obj_set_align(ui_bgroller, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bgroller, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bgroller, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Roller2 = lv_roller_create(ui_bgroller);
    lv_roller_set_options(ui_Roller2,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_Roller2, 98);
    lv_obj_set_width(ui_Roller2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller2, 0);
    lv_obj_set_y(ui_Roller2, -2);
    lv_obj_set_align(ui_Roller2, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_bg_color(ui_Roller2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bgroller1 = lv_img_create(ui_SETTIME);
    lv_img_set_src(ui_bgroller1, &ui_img_216451335);
    lv_obj_set_width(ui_bgroller1, LV_SIZE_CONTENT);   /// 52
    lv_obj_set_height(ui_bgroller1, LV_SIZE_CONTENT);    /// 102
    lv_obj_set_x(ui_bgroller1, 54);
    lv_obj_set_y(ui_bgroller1, -9);
    lv_obj_set_align(ui_bgroller1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bgroller1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bgroller1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Roller1 = lv_roller_create(ui_bgroller1);
    lv_roller_set_options(ui_Roller1,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_Roller1, 98);
    lv_obj_set_width(ui_Roller1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller1, 0);
    lv_obj_set_y(ui_Roller1, -2);
    lv_obj_set_align(ui_Roller1, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_bg_color(ui_Roller1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ok, ui_event_ok, LV_EVENT_ALL, NULL);

}
