// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_SET_DATE_screen_init(void)
{
    ui_SET_DATE = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SET_DATE, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bgsetdate = lv_img_create(ui_SET_DATE);
    lv_img_set_src(ui_bgsetdate, &ui_img_bggg_png);
    lv_obj_set_width(ui_bgsetdate, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_bgsetdate, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_align(ui_bgsetdate, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bgsetdate, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bgsetdate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_titlesdt4 = lv_label_create(ui_bgsetdate);
    lv_obj_set_width(ui_titlesdt4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_titlesdt4, LV_SIZE_CONTENT);    /// -83
    lv_obj_set_x(ui_titlesdt4, -3);
    lv_obj_set_y(ui_titlesdt4, 14);
    lv_obj_set_align(ui_titlesdt4, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_titlesdt4, "SET DATE");
    lv_obj_set_style_text_color(ui_titlesdt4, lv_color_hex(0x0CBCEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_titlesdt4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Calendar2 = lv_calendar_create(ui_SET_DATE);
    lv_obj_t * ui_Calendar2_header = lv_calendar_header_arrow_create(ui_Calendar2);
    lv_obj_set_width(ui_Calendar2, 230);
    lv_obj_set_height(ui_Calendar2, 240);
    lv_obj_set_x(ui_Calendar2, -1);
    lv_obj_set_y(ui_Calendar2, -3);
    lv_obj_set_align(ui_Calendar2, LV_ALIGN_CENTER);

    ui_ok1 = lv_btn_create(ui_SET_DATE);
    lv_obj_set_width(ui_ok1, 65);
    lv_obj_set_height(ui_ok1, 35);
    lv_obj_set_x(ui_ok1, 0);
    lv_obj_set_y(ui_ok1, 135);
    lv_obj_set_align(ui_ok1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ok1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ok1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_ok1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "OK");

    lv_obj_add_event_cb(ui_ok1, ui_event_ok1, LV_EVENT_ALL, NULL);

}
