// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_SETDAYTIME_screen_init(void)
{
    ui_SETDAYTIME = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SETDAYTIME, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_background3 = lv_img_create(ui_SETDAYTIME);
    lv_img_set_src(ui_background3, &ui_img_bggg_png);
    lv_obj_set_width(ui_background3, LV_SIZE_CONTENT);   /// 512
    lv_obj_set_height(ui_background3, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_align(ui_background3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_background3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_background3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HOME3 = lv_btn_create(ui_SETDAYTIME);
    lv_obj_set_width(ui_HOME3, 38);
    lv_obj_set_height(ui_HOME3, 38);
    lv_obj_set_x(ui_HOME3, 4);
    lv_obj_set_y(ui_HOME3, 4);
    lv_obj_add_flag(ui_HOME3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HOME3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HOME3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HOME3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HOME3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HOME3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_HOME3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_HOME3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HOME4 = lv_img_create(ui_HOME3);
    lv_img_set_src(ui_HOME4, &ui_img_house_png);
    lv_obj_set_width(ui_HOME4, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_HOME4, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_align(ui_HOME4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HOME4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HOME4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HOME4, lv_color_hex(0x060505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HOME4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeAna1 = lv_obj_create(ui_SETDAYTIME);
    lv_obj_set_width(ui_TimeAna1, 144);
    lv_obj_set_height(ui_TimeAna1, 58);
    lv_obj_set_x(ui_TimeAna1, 1);
    lv_obj_set_y(ui_TimeAna1, -94);
    lv_obj_set_align(ui_TimeAna1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TimeAna1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TimeAna1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TimeAna1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TimeAna1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TimeAna1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_houranalog1 = lv_label_create(ui_TimeAna1);
    lv_obj_set_width(ui_houranalog1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_houranalog1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_houranalog1, -37);
    lv_obj_set_y(ui_houranalog1, 0);
    lv_obj_set_align(ui_houranalog1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_houranalog1, "03");
    lv_obj_set_style_text_color(ui_houranalog1, lv_color_hex(0x02A5B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_houranalog1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_houranalog1, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dau2cham1 = lv_label_create(ui_TimeAna1);
    lv_obj_set_width(ui_dau2cham1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dau2cham1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dau2cham1, 3);
    lv_obj_set_y(ui_dau2cham1, -4);
    lv_obj_set_align(ui_dau2cham1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dau2cham1, ":");
    lv_obj_set_style_text_color(ui_dau2cham1, lv_color_hex(0x02A5B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dau2cham1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dau2cham1, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_minanalog1 = lv_label_create(ui_TimeAna1);
    lv_obj_set_width(ui_minanalog1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_minanalog1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_minanalog1, 42);
    lv_obj_set_y(ui_minanalog1, -1);
    lv_obj_set_align(ui_minanalog1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_minanalog1, "59");
    lv_obj_set_style_text_color(ui_minanalog1, lv_color_hex(0x02A5B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_minanalog1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_minanalog1, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DayANA1 = lv_obj_create(ui_SETDAYTIME);
    lv_obj_set_width(ui_DayANA1, 167);
    lv_obj_set_height(ui_DayANA1, 34);
    lv_obj_set_x(ui_DayANA1, 2);
    lv_obj_set_y(ui_DayANA1, -54);
    lv_obj_set_align(ui_DayANA1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_DayANA1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DayANA1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DayANA1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_namedateAna1 = lv_label_create(ui_DayANA1);
    lv_obj_set_width(ui_namedateAna1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_namedateAna1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_namedateAna1, -46);
    lv_obj_set_y(ui_namedateAna1, 0);
    lv_obj_set_align(ui_namedateAna1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_namedateAna1, "Tue");
    lv_obj_set_style_text_color(ui_namedateAna1, lv_color_hex(0x088CAB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_namedateAna1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_namedateAna1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dayana1 = lv_label_create(ui_DayANA1);
    lv_obj_set_width(ui_dayana1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dayana1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dayana1, 3);
    lv_obj_set_y(ui_dayana1, -1);
    lv_obj_set_align(ui_dayana1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dayana1, "4");
    lv_obj_set_style_text_color(ui_dayana1, lv_color_hex(0x088CAB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dayana1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dayana1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_namemonthana1 = lv_label_create(ui_DayANA1);
    lv_obj_set_width(ui_namemonthana1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_namemonthana1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_namemonthana1, 55);
    lv_obj_set_y(ui_namemonthana1, 0);
    lv_obj_set_align(ui_namemonthana1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_namemonthana1, "Jul");
    lv_obj_set_style_text_color(ui_namemonthana1, lv_color_hex(0x088CAB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_namemonthana1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_namemonthana1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BACK2 = lv_btn_create(ui_SETDAYTIME);
    lv_obj_set_width(ui_BACK2, 40);
    lv_obj_set_height(ui_BACK2, 41);
    lv_obj_set_x(ui_BACK2, 196);
    lv_obj_set_y(ui_BACK2, 4);
    lv_obj_add_flag(ui_BACK2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BACK2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BACK2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BACK2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BACK2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BACK2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BACK2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BACK2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BACK3 = lv_img_create(ui_BACK2);
    lv_img_set_src(ui_BACK3, &ui_img_backk_png);
    lv_obj_set_width(ui_BACK3, LV_SIZE_CONTENT);   /// 25
    lv_obj_set_height(ui_BACK3, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_BACK3, -1);
    lv_obj_set_y(ui_BACK3, -1);
    lv_obj_set_align(ui_BACK3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BACK3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BACK3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_titlesdt = lv_label_create(ui_SETDAYTIME);
    lv_obj_set_width(ui_titlesdt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_titlesdt, LV_SIZE_CONTENT);    /// -83
    lv_obj_set_x(ui_titlesdt, -3);
    lv_obj_set_y(ui_titlesdt, 14);
    lv_obj_set_align(ui_titlesdt, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_titlesdt, "SET DAY TIME");
    lv_obj_set_style_text_color(ui_titlesdt, lv_color_hex(0x0CBCEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_titlesdt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_SETDAYTIME);
    lv_obj_set_width(ui_Button1, 72);
    lv_obj_set_height(ui_Button1, 36);
    lv_obj_set_x(ui_Button1, 62);
    lv_obj_set_y(ui_Button1, 20);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button2 = lv_btn_create(ui_SETDAYTIME);
    lv_obj_set_width(ui_Button2, 72);
    lv_obj_set_height(ui_Button2, 36);
    lv_obj_set_x(ui_Button2, -62);
    lv_obj_set_y(ui_Button2, 20);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button3 = lv_btn_create(ui_SETDAYTIME);
    lv_obj_set_width(ui_Button3, 72);
    lv_obj_set_height(ui_Button3, 36);
    lv_obj_set_x(ui_Button3, -3);
    lv_obj_set_y(ui_Button3, 110);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_SETDAYTIME);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -63);
    lv_obj_set_y(ui_Label6, 20);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "SET TIME");

    ui_Label4 = lv_label_create(ui_SETDAYTIME);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 62);
    lv_obj_set_y(ui_Label4, 20);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "SET DATE");

    ui_Label9 = lv_label_create(ui_SETDAYTIME);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -4);
    lv_obj_set_y(ui_Label9, 110);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "SAVE");

    lv_obj_add_event_cb(ui_HOME3, ui_event_HOME3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BACK2, ui_event_BACK2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);

}
